name: Deploy Cube Automation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}

          script: |
            set -e

            cd /var/www/cube-automation

            echo "Pull latest code..."
            git fetch origin
            git reset --hard origin/main

            echo "Backend..."
            cd backend
            source venv/bin/activate
            pip install -r requirements.txt

            sudo systemctl restart cube-automation.service

            echo "Frontend..."
            cd ../frontend
            npm install
            npm run build

            sudo nginx -t
            sudo systemctl reload nginx

            echo "Deployment completed."
